#!/bin/bash

set -eu pipefail
hostname -I

apt-get install -y sysstat wget vim policycoreutils selinux-utils selinux-basics vim iputils-ping dnsutils bridge-utils openssl build-essential netcat-traditional net-tools iptables apt-transport-https curl git ca-certificates software-properties-common git
apt-get upgrade -y && apt-get -y update
sed -i 's/ENABLED="false"/ENABLED="true"/g' /etc/default/sysstat && cat /etc/default/sysstat
sudo grep -q "^govadmin ALL=(ALL) NOPASSWD:ALL" /etc/sudoers || echo "govadmin ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
sudo sudo sed -i '/^[^#]*swap/s/^/#/' /etc/fstab
sudo apt update -y
sudo apt install -y software-properties-common curl apt-transport-https ca-certificates curl gnupg gnupg2

echo "overlay" | sudo tee -a /etc/modules-load.d/k8s.conf
echo "br_netfilter" | sudo tee -a /etc/modules-load.d/k8s.conf
sudo modprobe overlay ; sudo modprobe br_netfilter
 
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
sudo sysctl -w net.bridge.bridge-nf-call-iptables=1
sudo sysctl -w net.bridge.bridge-nf-call-ip6tables=1
sudo sysctl -w net.ipv4.ip_forward=1
sudo sysctl -p ; sysctl --system

echo "Installing CRI-O Runtime on All the Nodes............................."
sudo rm /etc/apt/keyrings/cri-o-apt-keyring.gpg ; sudo curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
sudo echo "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/ /" | sudo tee /etc/apt/sources.list.d/cri-o.list
sudo apt-get update -y
sudo apt-get install -y cri-o

sudo systemctl daemon-reload
sudo systemctl enable crio --now
sudo systemctl start crio.service

echo "Install Kubeadm & Kubelet & Kubectl on all Nodes.........."

sudo rm -rf /etc/apt/keyrings/kubernetes-apt-keyring.gpg
export K8_VERSION="v1.30"
sudo curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor --batch -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/${K8_VERSION}/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo apt update -y
sudo apt install -y kubeadm=1.30.0-1.1 kubelet=1.30.0-1.1 kubectl=1.30.0-1.1
sudo apt-mark hold kubelet=1.30.0-1.1 kubeadm=1.30.0-1.1 kubectl=1.30.0-1.1
 
# Installing Helm-3 only on master or in your local machine
# Reference Ducument for new available version: https://helm.sh/docs/intro/install/
# curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
 
echo "Installation Finished of  CRI-O Runtime on All the Nodes............................."
